name: Deploy To S3

on:
  push:
    branches:
      - dev

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.16.0

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: |
          npm install --save-dev @babel/plugin-proposal-private-property-in-object
          npm run build
        env:
          CI: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Delete existing files from S3
        run: aws s3 rm s3://mini-game-world-web --recursive --include "*"

      - name: Upload new files to S3
        run: aws s3 cp ./build s3://mini-game-world-web/ --recursive

      - name:  Cloudfront 캐시 무효화
        run: aws cloudfront create-invalidation --distribution-id E1WQE1CPEFVIRJ --paths "/*"
